version: "3.9"

on:
  workflow_dispatch

env: 
  DOCKER_USERNAME:
  IMAGE_NAME: massai_mara
  IMAGE_TAB: 

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: massai_mara:v2
    container_name: massai_mara_app
    ports: 
      - "8080:8080"
